table: directus_settings

fields:
  - field: id
    hidden: true

  - field: project_name
    interface: text-input
    options:
      iconRight: title
      placeholder: $t:field_options.directus_settings.project_name_placeholder
    translations:
      language: en-US
      translations: Name
    width: half

  - field: project_url
    interface: text-input
    options:
      iconRight: link
      placeholder: https://example.com
    translations:
      language: en-US
      translations: Website
    width: half

  - field: project_color
    interface: color
    note: $t:field_options.directus_settings.project_color_note
    translations:
      language: en-US
      translations: Brand Color
    width: half

  - field: project_logo
    interface: file
    note: $t:field_options.directus_settings.project_logo_note
    translations:
      language: en-US
      translations: Brand Logo
    width: half

  - field: public_divider
    interface: divider
    options:
      icon: public
      title: $t:field_options.directus_settings.public_divider_title
    special:
      - alias
      - no-data
    width: full

  - field: public_foreground
    interface: file
    translations:
      language: en-US
      translations: Login Foreground
    width: half

  - field: public_background
    interface: file
    translations:
      language: en-US
      translations: Login Background
    width: half

  - field: public_note
    interface: textarea
    options:
      placeholder: $t:field_options.directus_settings.public_note_placeholder
    width: full

  - field: security_divider
    interface: divider
    options:
      icon: security
      title: $t:field_options.directus_settings.security_divider_title
    special:
      - alias
      - no-data
    width: full

  - field: auth_password_policy
    interface: dropdown
    options:
      choices:
        - value: null
          text: $t:field_options.directus_settings.auth_password_policy.none_text
        - value: '/^.{8,}$/'
          text: $t:field_options.directus_settings.auth_password_policy.weak_text
        - value: "/(?=^.{8,}$)(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+}{';'?>.<,])(?!.*\\s).*$/"
          text: $t:field_options.directus_settings.auth_password_policy.strong_text
    width: half

  - field: auth_login_attempts
    interface: numeric
    options:
      iconRight: lock
    width: half

  - field: files_divider
    interface: divider
    options:
      icon: storage
      title: $t:field_options.directus_settings.files_divider_title
    special:
      - alias
      - no-data
    width: full

  - field: storage_asset_presets
    interface: repeater
    options:
      fields:
        - field: key
          name: $t:key
          type: string
          schema:
            is_nullable: false
          meta:
            interface: slug
            options:
              onlyOnCreate: false
            width: half
        - field: fit
          name: $t:fit
          type: string
          schema:
            is_nullable: false
          meta:
            interface: dropdown
            options:
              choices:
                - value: contain
                  text: $t:field_options.directus_settings.storage_asset_presets.fit.contain_text
                - value: cover
                  text: $t:field_options.directus_settings.storage_asset_presets.fit.cover_text
                - value: inside
                  text: $t:field_options.directus_settings.storage_asset_presets.fit.fit_text
                - value: outside
                  text: $t:field_options.directus_settings.storage_asset_presets.fit.outside_text
            width: half
        - field: width
          name: $t:width
          type: integer
          schema:
            is_nullable: false
          meta:
            interface: numeric
            width: half
        - field: height
          name: $t:height
          type: integer
          schema:
            is_nullable: false
          meta:
            interface: numeric
            width: half
        - field: quality
          type: integer
          name: $t:quality
          schema:
            default_value: 80
            is_nullable: false
          meta:
            interface: slider
            options:
              max: 100
              min: 0
              step: 1
            width: half
        - field: withoutEnlargement
          type: boolean
          schema:
            default_value: false
          meta:
            interface: toggle
            width: half
            options:
              label: $t:no_upscale
      template: '{{key}}'
    special: json
    width: full

  - field: storage_asset_transform
    interface: dropdown
    options:
      choices:
        - value: all
          text: $t:all
        - value: none
          text: $t:none
        - value: presets
          text: $t:presets
    width: half

  - field: overrides_divider
    interface: divider
    options:
      icon: brush
      title: $t:field_options.directus_settings.overrides_divider_title
    special:
      - alias
      - no-data
    width: full

  - field: custom_css
    interface: code
    options:
      language: css
      lineNumber: true
    width: full
